---
- hosts: all
  vars:
    app_root: '/vagrant'
    app_user: vagrant
    app_public: "{{app_root}}/public"
    roles_path: '../../ansible-provisioner/roles'

  roles:
    - "{{roles_path}}/init"
    - "{{roles_path}}/ruby"
    - "{{roles_path}}/nodejs"
    - "{{roles_path}}/python-tools"
    - "{{roles_path}}/mongodb"
    - "{{roles_path}}/nginx"
